### PR TITLE
Add footer with link to repository

### LINKED ISSUE #9: Add footer with repo link
Currently there is no way to go from the website to the repo.

Add a footer with link to repo.

### PR DESCRIPTION
**Pull request by akshat157**
Fix #9 
Hope this does the job! :grin: 

Edit: Please squash and merge (Only the last commit is useful, had some difficulties) , and if required, change any properties you want to.

Edit 2: Screenshot added.
Screenshot from 2019-10-03 23-04-45

### CODE REVIEW

**Review by LewisSama — CHANGES_REQUESTED** [review]
Hi, i've been looking for a Hacktober project and found this issue. I was working on it but i saw your submit. Great work ! I can suggest you to had a background to separate it visually from the rest of the body.
`background-color: #B8860B`
This color may be a good choice to fit in a potatoes theme ! 
And also a padding-top to give an airing under the potatoe.
`padding-top: 20px;`
Good spooky Hacktober *DOOT* !

**Comment by akshat157** [comment]
@LewisSama That's something I thought to add myself, not lying. Thanks mate!

Edit: Also, there are a few to-be-worked-upon projects of my own if you're looking for something to contribute to. :smile:

**Review by viniciuskneves — COMMENTED** [review]
Super cool man, thanks for that. I'm going to give it a try today/tomorrow and get back to you asap.

Nevertheless, could you just add Gitmoji to your commits and follow the contribution guidelines? https://github.com/viniciuskneves/ichbineinekartoffel.de#contribution-guidelines --> It is just a funny thing, hope you enjoy finding the right Gitmoji 😄

**Review by viniciuskneves — CHANGES_REQUESTED** [review]
Hey, super liked the result but I want to point some stuffs:
- Lighthouse SEO score got penalized as `<a>` doesn't have a descriptive text (https://developers.google.com/web/tools/lighthouse/audits/descriptive-link-text): I do recommend making `Contribute` itself as a link.
- Once you hover the link it becomes really hard to understand. Consider using a better contrast.
Link with no hover
Link with hover and bad contrast

Thank you very much for your effort here!

**Comment by akshat157** [comment]
Okay, so

1. I have to make `Contribute` the only link.
2. I've to add a Gitmoji to the commit message.
3. I've to change the hover color / make it properly visible.

I believe this is all. Will soon do it! :smile:

**Comment by akshat157** [comment]
@viniciuskneves Did the requested changes and requested a review. Hope its fine now. :smile:

**Comment by viniciuskneves** [comment]
It is great now but unfortunately the last merge introduced some conflicts :/

Is it possible to fix it? I will merge as soon as it it possible 😄

**Review by viniciuskneves — APPROVED** [review]

**Comment by akshat157** [comment]
I hope the conflicts are resolved now. Although, I'd request you to check once before merging if the file's fine now.

**Comment by akshat157** [comment]
I hope the conflicts are resolved now. I'll still suggest you to check once before merging if the file's fine now.

**Pull request merged**
